In [1]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv('final_jobs.csv')
df.head()

             company        location company_id
0        CyberCoders   alexandria va      21836
1  Johnson   Johnson  santa clara ca       1207
2          Microsoft   washington dc       1035
3          Microsoft       reston va       1035
4          Microsoft          irv tx       1035

In [19]:
df.replace(r'^\s*$', pd.NA, regex=True, inplace=True)
df.dropna(inplace=True)

In [20]:
df.shape

(7780, 3)

In [21]:
df.head(50)

                company         location company_id
0           CyberCoders    alexandria va      21836
1     Johnson   Johnson   santa clara ca       1207
2             Microsoft    washington dc       1035
3             Microsoft        reston va       1035
4             Microsoft           irv tx       1035
5             Microsoft       atlanta ga       1035
6             Microsoft      charlott nc       1035
7               Cleerly        denver co   34949677
8             Microsoft        reston va       1035
9             Microsoft      charlott nc       1035
10            Microsoft       atlanta ga       1035
11            Microsoft    washington dc       1035
12            Microsoft           irv tx       1035
13            Microsoft       redmond wa       1035
14    Johnson   Johnson        seattl wa       1207
15      The Shade Store  port chester ny    1243847
16            Microsoft       chicago il       1035
17    Johnson   Johnson        seattl wa       1207
18            Microsoft     san diego ca       1035
19            Microsoft      charlott nc       1035
20            Microsoft    washington dc       1035
21            Microsoft        reston va       1035
22            Microsoft         miami fl       1035
23    Johnson   Johnson      titusvil nj       1207
24            Microsoft       atlanta ga       1035
25          CyberCoders        oviedo fl      21836
26      PatientPop Inc.      lo angel ca    3575867
27             Mindtree       bellevu wa       4300
28  Minuteman Group LLC     lexington ma    1136838
29               Rapid         boston ma      39624
30          CyberCoders      new york ny      21836
31             MuleSoft         tampa fl      64251
32               NetSPI          lehi ut     283714
33             MuleSoft         dalla tx      64251
34          CyberCoders       nashvil tn      21836
35             MuleSoft        denver co      64251
36          CyberCoders      charlott nc      21836
37             MuleSoft   indianapoli in      64251
38             MuleSoft       unit state      64251
39             MuleSoft       atlanta ga      64251
40             MuleSoft  greater houston      64251
41             MuleSoft  utah unit state      64251
42             MuleSoft         miami fl      64251
43             MuleSoft        austin tx      64251
44             MuleSoft        denver co      64251
45             MuleSoft       raleigh nc      64251
46             MuleSoft        austin tx      64251
47             MuleSoft   indianapoli in      64251
48             MuleSoft       bellevu wa      64251
49             MuleSoft       atlanta ga      64251

In [22]:
df.to_csv('company.csv', index=False)